version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlpreview
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd
      - MSSQL_PID=Evaluation
    ports:
      - "1433:1433"
    networks:
      - my_network
    volumes:
      - ./sql-scripts:/var/opt/mssql/scripts
    command: /opt/mssql/bin/sqlservr

  productmanagementapi:
    build:
      context: ./PodBooking
      dockerfile: Dockerfile
    container_name: productmanagementapi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlpreview;Database=SWP391;User Id=sa;Password=StrongP@ssw0rd;TrustServerCertificate=True;
    ports:
      - "8888:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

    
